#Multithreading With Thread Pool Executor

'''
Thread Pool Executor is high level abstraction which creates a max number of workers and assign the task to these workers, and allow the reusability, means if max worker is 3 and 5 task to 
perform, so we can execute 3 task concurrently with 3 threads and let 2 left task wait in the queue.

Earlier we were creating the Threads manually, starting them, joining them and manage lifecycle. Thread pool executor does everything automatically.
We need it because, there can be many tasks, and we dont know how many threads we need, and wants clean code so threadpoolexecutor handles all these

Thread Pool: means instead of creating the thread for each task, we create fix no.of threads once, then reuse them for multiple task
'''

from concurrent.futures import ThreadPoolExecutor
import time 

def print_number(number) :
    time.sleep(1)
    return f"Number: {number}"

numbers = [1,2,3,4,5]

#here with keyword ensure that all the threads are executed then only move ahead i.e like .join() to pause the main thread
with ThreadPoolExecutor(max_workers=3) as executor :
    '''
    Here we have .map() method send the list of tasks at once and all the results, as map function we studied it apply function to each element of iterable i.e
    Task1: print_number(1), Task2: print_number(2)... so on, the results generated by each task is stored within the "results" iterator and that too in intact order of each task send
    '''
    results = executor.map(print_number, numbers)

for result in results :
    print(result)



'''
There is also executor.submit(task, i) method which send the single job at a time providing more flexibility to handle each task
ex: 
for i in range(5):
    executor.submit(task, i)
Here: Thread1: task(1), Thread2: task(2).. so on creates 5 tasks.
Now each task return a future object i.e future = executor.submit(function, argument), here future object that represents the results of each task which will be available later 
To see the result we can just use: future.result() to get the result of each task using .submit() method
'''
